export const metadata = {
  title: "aplicacion",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav>
          <h1>Enlaces</h1>
          <a href="/about">Acerca de nosotros</a>
        </nav>
        {children}
      </body>
      {/* para que reconozca todas las rutas desde aqui */}
    </html>
  );
}
