export const metadata = {
  title: "aplicacion",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
      {/* para que reconozca todas las rutas desde aqui */}
    </html>
  );
}
